defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.0

version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo