defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.0

whitelist: &whitelist
  paths:
    - .npmignore
    - coverage/*
    - dist/*
    - lib/*
    - node_modules/*
    - src/*
    - test/*
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json
    - jestconfig.json
    - pbweb/*
    - pbnode/*

version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json "}}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run: 
          name: Test with Coverage
          command: npm run test:cov
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - test
